import type { Metadata } from 'next'
/* eslint-disable camelcase */
import { Space_Grotesk } from 'next/font/google'
import './globals.css'

const spaceGrotesk = Space_Grotesk({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Samuell Targino | Desenvolvedor de sites, lojas e aplicações web',
  description: 'Generated by create next app',
  icons: {
    icon: [
      {
        url: '/favicon.svg',
      },
    ],
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={spaceGrotesk.className}>{children}</body>
    </html>
  )
}
